# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 38e76dfb5740314dbc3a899f3b451ec2e24ec0d3e4119f4309e5332783c81c0c46f5ba8a3148b24057f8ece8ce4c442fbda3f765266caf8b61d51ee78c9fa83a

test:
  secret_key_base: db66f08f553d0826395d1dc423563fac14c2f753353332de2e0d37319bf5e911c7c0a063a0889ee6a483b897380e9f24bf736b9c03551b2adc87c62ed51e668d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
